# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.5
python: 3.5

# Install the library dependcies
install:
  - pip3 install pandas numpy matplotlib

# Run various python files in the project
script:
  - python3 ransac.py
  - python3 svd_simple.py